##############################################################################
# CI for CEPCSW at IHEP GitLab
##############################################################################

stages:
  - build
  # - test

##############################################################################
# Build Template
##############################################################################
.build_template:
  stage: build
  variables:
    LCG_RELEASE:
    CEPCSW_BLDTOOL: ninja
  script:
    - bash ./.build.ci.sh


##############################################################################
# Build CentOS 7 (LCG)
##############################################################################
build:lcg:el7:
  extends: .build_template
  variables:
    LCG_RELEASE: LCG

##############################################################################
# Build CentOS 7 (KEY4HEP)
##############################################################################
build:k4:el7:
  extends: .build_template
  variables:
    LCG_RELEASE: KEY4HEP_STACK

